### ISSUE TITLE
Typing return non-Korean characters

### ISSUE THREAD

**Issue by jgratero** [hamonikr/hamonikr-onboard-layout-ko#4]
**버그가 발생한 환경을 알려주세요:**
 - OS: [e.g. HamoniKR 3.0] 
 - Browser [e.g. chrome, whale]
 - Version [e.g. 1.0.1] (dpkg -l | grep onboard-ko 로 확인가능)

This happened in Sparky Linux 5.16, Debian based.

**버그 내용 설명(Describe the bug)**
자세한 버그 내용을 설명해주세요.

Whenever I try to use the keyboard with the Korean layout, it return non-Korean characters.

**To Reproduce**

어떤 과정으로 재현되는지 알려주세요.

Select Korean layout, Type.

**Expected behavior**

예상한 결과가 무엇인지 알려주세요.

Typing return non-Korean characters and special characters. 

**Screenshots**
오류 화면이 있으면 업로드 해주세요.
(이미지를 입력창에 마우스로 드래그앤드롭 하시면 자동으로 이미지가 업로드 됩니다.)

**Additional context**
문제를 설명할 다른 추가 내용이 있으면 설명해주세요.

**Comment by chaeya** [comment]
![image](https://user-images.githubusercontent.com/405502/224225030-53b5a62e-0800-46d4-a9b2-34a74c82b6be.png)

As a result of testing with the following process on Sparky Linux 7, which is currently available for testing, I confirmed that Korean characters were normally input.

1) First, it is necessary for Korean input to be normal in the system.
2) Install the onboard program.
3) Install this project that extends the functionality of the onboard program.

![image](https://user-images.githubusercontent.com/405502/224225259-9d31bb43-8019-46b3-b031-807ca03aaa36.png)
